# Generated by Django 4.2.6 on 2023-10-28 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0004_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
