# Generated by Django 4.2.6 on 2023-10-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cake', '0005_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('password', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
