# Generated by Django 4.2.6 on 2023-10-28 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
