# Generated by Django 4.2.6 on 2023-10-29 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0009_alter_signup_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='email',
            new_name='username',
        ),
    ]
