# Generated by Django 4.2.6 on 2023-10-30 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0012_alter_signup_options_alter_signup_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactFormEntry',
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
