# Generated by Django 4.2.6 on 2023-10-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0015_alter_signup_options_alter_signup_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
