# Generated by Django 4.2.6 on 2023-10-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0017_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_eggless',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price_half_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='price_one_and_half_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='price_one_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(choices=[('0.5', 'Half Kg'), ('1.0', '1 Kg'), ('1.5', '1.5 Kg')], default='0.5', max_length=3),
        ),
    ]
