# Generated by Django 4.2.6 on 2023-10-30 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0018_remove_product_is_eggless_remove_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
    ]
