# Generated by Django 4.2.6 on 2023-10-31 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0021_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_half_kg',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_one_and_half_kg',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_one_kg',
            field=models.IntegerField(),
        ),
    ]
