# Generated by Django 4.2.6 on 2023-10-31 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0022_alter_product_price_half_kg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
